project:
  type: website
  title: "HOAD Dashboard"
  output-dir: docs

website:
  title: "HOAD"
  navbar:
    background: primary
    left:
      - text: "Home"
        file: index.qmd
      - text: "Dashboards"
        menu:
        - text: "Journal Checker Tool (JCT)" 
          file: jct.qmd
        - text: "FZ Jülich Open Access Monitor (OAM)"
          file: oam.qmd 
  page-footer:
    left: |
      Developed at the <a href="https://www.sub.uni-goettingen.de/sub-aktuell/">Göttingen State and University Library</a>
    center:
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license.qmd
      - text: "Imprint"
        href: https://www.sub.uni-goettingen.de/impressum/
    right:
      - icon: github
        href: https://github.com/subugoe/hoaddash/
        aria-label: Project GitHub

format:
  html:
    theme:
      - cosmo
      - styles.scss