project:
  type: website
  title: "HOAD Dashboard"
  output-dir: docs
  execute-dir: project

website:
  title: "HOAD"
  page-footer:
    left: |
      Developed at the <a href="https://www.sub.uni-goettingen.de/sub-aktuell/">Göttingen State and University Library</a>
    center:
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license.qmd
      - text: "Imprint"
        href: https://www.sub.uni-goettingen.de/impressum/
    right:
      - icon: github
        href: https://github.com/subugoe/hoaddash/
        aria-label: Project GitHub
  sidebar:
    background: "#ffffff"
    border: false
    logo: "hoad_logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/subugoe/hoaddash
        text: "GitHub Repo"
      - icon: bar-chart
        href: https://github.com/subugoe/hoaddata
        text: "Data"
      - icon: person-fill
        text: "Contact"
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - section: "Hybrid Open Access Publishers"
        contents:
          - href: jct/index.qmd
            text: Overview
          - href: jct/elsevier/index.qmd
            text: "Elsevier"
          - href: jct/springernature/index.qmd
            text: Springer Nature
          - href: jct/wiley/index.qmd
            text: Wiley
          - section: "Others"
            contents: 
               - href: jct/taylor&francis/index.qmd
                 text: Taylor & Francis
               - text: "IEEE"
                 href: jct/ieee/index.qmd
               - text: American Chemical Society 
                 href: jct/americanchemicalsociety/index.qmd
               - text: "Oxford University Press"
                 href: jct/oxforduniversitypress/index.qmd
               - text: "Sage"
                 href: jct/sage/index.qmd
               - text: "Royal Society of Chemistry"
                 href: jct/royalsocietyofchemistry/index.qmd
               - text: "Cambridge University Press"
                 href: jct/cambridgeuniversitypress/index.qmd
               - text: "IOP Publishing"
                 href: jct/ioppublishing/index.qmd
               - text: "Walter de Gruyter"
                 href: jct/walterdegruyter/index.qmd
               - text: "American Physical Society"
                 href: jct/thieme/index.qmd
               - text: "Thieme"
                 href: jct/karger/index.qmd
               - text: "Karger"
                 href: jct/benthamsciencepublishers/index.qmd
               - text: "Bentham Science Publishers"
                 href: jct/benthamsciencepublishers/index.qmd
               - text: "BMJ Publishing"
                 href: jct/bmjpublishing/index.qmd
      - section: "Germany-wide transformative agreements"
        contents:
          - href: oam/cupbsb/index.qmd
            text: Overview

format:
  html:
    theme:
      light: [cosmo, styles.scss]
    mainfont: "Atkinson Hyperlegible"
      
execute:
  cache: true